using System;
using System.Collections.Generic; // Add for List
using System.Linq;
using Business.Forms;
using Business.Interfaces;
using Business.Models;
using Data.Entities;
using Domain.Models;

namespace Business.Factories
{
    /// <summary>
    /// Factory responsible for creating and mapping Project-related objects
    /// (Entities, Models, Forms, ListItems) between different layers.
    /// Handles default image assignment and random gradient selection for new projects.
    /// </summary>
    public class ProjectFactory : IProjectFactory
    {
        // List of predefined gradient
        // Generated by Gemini 2.5
        private static readonly List<string> _projectGradients = new List<string>
        {
            "linear-gradient(140deg, #FEC887 0%, #F9A486 100%)", // Orange/Peach
            "linear-gradient(140deg, #A091FB 0%, #C08AFB 100%)", // Purple
            "linear-gradient(140deg, #90E6AA 0%, #A3F0BE 100%)", // Green
            "linear-gradient(140deg, #84D9F8 0%, #90E0EF 100%)", // Blue
            "linear-gradient(140deg, #F6A0B6 0%, #F8B5C8 100%)", // Pink
        };
        private static readonly Random _random = new Random();

        /// <summary>
        /// Creates a new <see cref="ProjectEntity"/> from an <see cref="AddProjectForm"/>.
        /// Assigns default image and random gradient if not provided.
        /// </summary>
        /// <param name="form">The form data for the new project.</param>
        /// <param name="userId">The ID of the user creating the project.</param>
        /// <param name="clientName">The name of the client associated with the project.</param>
        /// <param name="imageUrl">Optional URL of an uploaded image for the project.</param>
        /// <returns>A new <see cref="ProjectEntity"/> instance.</returns>
        public ProjectEntity CreateProjectEntity(
            AddProjectForm form,
            string userId,
            string clientName,
            string? imageUrl = null // Keep allowing specific uploads
        )
        {
            string finalImageUrl = imageUrl;
            // If no image uploaded, use the default project icon
            if (string.IsNullOrEmpty(finalImageUrl))
            {
                finalImageUrl = "/images/projectimage.svg"; // Default icon path
            }

            // Select a random gradient
            string randomGradient = string.Empty;
            if (_projectGradients.Any())
            {
                int randomIndex = _random.Next(_projectGradients.Count);
                randomGradient = _projectGradients[randomIndex];
            }

            return new ProjectEntity
            {
                Name = form.Name,
                ClientName = clientName,
                Description = form.Description ?? string.Empty,
                StartDate = form.StartDate,
                EndDate = form.EndDate,
                Budget = form.Budget,
                CreatedAt = DateTime.UtcNow,
                IsActive = form.IsActive,
                ImageUrl = finalImageUrl, // Use default or uploaded image
                ClientId = form.ClientId,
                StatusId = form.StatusId,
                UserId = userId,
                GradientCss = randomGradient, // Assign the random gradient (New Property)
            };
        }

        /// <summary>
        /// Updates an existing <see cref="ProjectEntity"/> with data from an <see cref="EditProjectForm"/>.
        /// </summary>
        /// <param name="entity">The existing project entity to update.</param>
        /// <param name="form">The form data containing updates.</param>
        /// <param name="imageUrl">Optional new image URL if the image was updated.</param>
        /// <returns>The updated <see cref="ProjectEntity"/> instance.</returns>
        public ProjectEntity UpdateProjectEntity(
            ProjectEntity entity,
            EditProjectForm form,
            string? imageUrl = null
        )
        {
            entity.Name = form.Name;
            entity.ClientName = form.ClientName;
            entity.Description = form.Description ?? string.Empty; // Handle null description
            entity.StartDate = form.StartDate;
            entity.EndDate = form.EndDate;
            entity.Budget = form.Budget;
            entity.IsActive = form.IsActive;
            entity.StatusId = form.StatusId; // Update the status ID
            entity.UpdatedAt = DateTime.UtcNow;

            // Only update image if a new one is provided
            if (imageUrl != null)
            {
                entity.ImageUrl = imageUrl ?? string.Empty; // Handle null image URL
            }

            return entity;
        }

        /// <summary>
        /// Creates a <see cref="ProjectListItem"/> suitable for display in lists from a <see cref="ProjectEntity"/>.
        /// Requires `Status` and `Members` navigation properties to be loaded on the entity.
        /// </summary>
        /// <param name="entity">The project data entity (with Status and Members loaded).</param>
        /// <returns>A new <see cref="ProjectListItem"/> instance.</returns>
        public ProjectListItem CreateProjectListItem(ProjectEntity entity)
        {
            return new ProjectListItem
            {
                Id = entity.Id,
                Name = entity.Name,
                ClientName = entity.ClientName,
                Description = entity.Description,
                StartDate = entity.StartDate,
                EndDate = entity.EndDate,
                Budget = entity.Budget ?? 0, // Handle nullable budget
                IsActive = entity.IsActive,
                ImageUrl = entity.ImageUrl,
                // MemberCount = entity.Members?.Count ?? 0, // Replaced by avatar list
                CreatedAt = entity.CreatedAt,
                StatusId = entity.StatusId ?? string.Empty, // Assign StatusId
                // Ensure entity.Status is loaded for this to work
                StatusName = entity.Status?.Name ?? "Unknown", // Assign StatusName (handle potential null navigation property)
                GradientCss = entity.GradientCss ?? string.Empty, // Assign GradientCss
                // Ensure entity.Members and their ImageUrl are loaded
                MemberAvatarUrls =
                    entity
                        .Members?.Select(m => m.ImageUrl ?? "/images/Avatar.png") // Use default if null
                        .ToList() ?? new List<string>(),
            };
        }

        /// <summary>
        /// Creates an <see cref="EditProjectForm"/> from a <see cref="ProjectEntity"/> for editing purposes.
        /// Requires the `Members` navigation property to be loaded on the entity.
        /// </summary>
        /// <param name="entity">The project data entity (with Members loaded).</param>
        /// <returns>A new <see cref="EditProjectForm"/> instance.</returns>
        public EditProjectForm CreateEditProjectForm(ProjectEntity entity)
        {
            return new EditProjectForm
            {
                Id = entity.Id,
                Name = entity.Name,
                ClientName = entity.ClientName,
                Description = entity.Description ?? string.Empty, // Handle potential null from DB? (Unlikely but safe)
                StartDate = entity.StartDate,
                EndDate = entity.EndDate,
                Budget = entity.Budget ?? 0, // Handle nullable budget
                IsActive = entity.IsActive,
                StatusId = entity.StatusId, // Include the status ID
                MemberIds = entity.Members?.Select(m => m.Id).ToList() ?? new List<string>(),
            };
        }

        /// <summary>
        /// Creates a <see cref="Project"/> business model from a <see cref="ProjectEntity"/>.
        /// Requires the `Members` navigation property to be loaded on the entity.
        /// </summary>
        /// <param name="entity">The project data entity (with Members loaded).</param>
        /// <returns>A new <see cref="Project"/> business model instance.</returns>
        public Project CreateProjectModel(ProjectEntity entity)
        {
            return new Project
            {
                Id = entity.Id,
                Name = entity.Name,
                ClientName = entity.ClientName,
                Description = entity.Description,
                StartDate = entity.StartDate,
                EndDate = entity.EndDate,
                Budget = entity.Budget ?? 0, // Handle nullable budget
                CreatedAt = entity.CreatedAt,
                UpdatedAt = entity.UpdatedAt,
                IsActive = entity.IsActive,
                Members =
                    entity
                        .Members?.Select(m => new Member
                        {
                            Id = m.Id,
                            FirstName = m.FirstName,
                            LastName = m.LastName,
                            Email = m.Email ?? string.Empty,
                            JobTitle = m.JobTitle ?? string.Empty,
                            Phone = m.PhoneNumber ?? string.Empty,
                        })
                        .ToList() ?? new List<Member>(),
            };
        }
    }
}
